apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}-service
spec:
  selector:
    app: {{ .Values.name | trunc 63 | trimSuffix "-" }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }} # The port the Service exposes internally within the cluster
      targetPort: {{ .Values.containerPort }} # The port on the Pod where the application is listening
      nodePort: {{ .Values.nodePort }} # Optional: A specific port on the Node (must be in the range 30000-32767)