apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nome | trunc 63 | trimSuffix "-" }}-service
spec:
  selector:
    app: {{ .Values.nome | trunc 63 | trimSuffix "-" }}
  ports:
    - protocol: TCP
      port: 5008
      targetPort: 5008