{{- if hasKey .Values "volumes" }}
{{- range $k, $v := .Values.volumes }}
{{- if not $v.ignore }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-storage-class-{{ $.Values.login | trunc 63 | trimSuffix "-" }}-{{ $v.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
{{- end }}
{{- end }}
{{- end}}